# Generated by Django 6.0.3 on 2026-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatushistory',
            options={'ordering': ['-timestamp']},
        ),
    ]
