# Generated by Django 6.0.3 on 2026-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size_in_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='Success', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8)),
                ('require_complexity', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30)),
                ('force_password_change', models.BooleanField(default=False)),
                ('last_backup_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
            },
        ),
    ]
