# Generated by Django 6.0.3 on 2026-04-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backupsnapshot_systemconfig'),
        ('accounts', '0005_employeeprofile_can_self_upload'),
    ]

    operations = [
    ]
