# Generated by Django 6.0.3 on 2026-04-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
