# Generated by Django 6.0.3 on 2026-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Leave Update', 'Leave Update'), ('Pending Approval', 'Pending Approval'), ('System Announcement', 'System Announcement')], max_length=50),
        ),
    ]
