# Generated by Django 6.0.3 on 2026-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('UNDERTIME', 'Undertime')], default='ABSENT', max_length=10),
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='edit_note',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='edited_at',
        ),
    ]
